apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          # kubectl create secret generic auth-service-secrets \
          #   --from-literal=DATABASE_URL="postgresql://..." \
          #   --from-literal=REDIS_URL="redis://redis-master:6379" \
          #   --from-literal=PRIVATE_KEY_PEM="$(cat private.pem)" \
          #   --from-literal=PUBLIC_KEY_PEM="$(cat public.pem)"
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          env:
            - name: SERVICE_NAME
              value: auth-service
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: production
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
